name: Build (debugGOTY)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild PlantsVsZombies.sln /p:Configuration=debugGOTY

    - name: Upload Artifact
      uses: actions/upload-artifact@main
      with:
        name: StableDecompile-debugGOTY-Build
        path: |
          Output/
